config/routes.rb
Rails.application.routes.draw do
  resources :parts
  resources :frames
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/frame.rb
class Frame < ApplicationRecord
end

app/models/part.rb
class Part < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
  before_action :set_frame, only: %i[ show edit update destroy ]

  # GET /frames or /frames.json
  def index
    @frames = Frame.all
  end

  # GET /frames/1 or /frames/1.json
  def show
  end

  # GET /frames/new
  def new
    @frame = Frame.new
  end

  # GET /frames/1/edit
  def edit
  end

  # POST /frames or /frames.json
  def create
    @frame = Frame.new(frame_params)

    respond_to do |format|
      if @frame.save
        format.html { redirect_to frame_url(@frame), notice: "Frame was successfully created." }
        format.json { render :show, status: :created, location: @frame }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frames/1 or /frames/1.json
  def update
    respond_to do |format|
      if @frame.update(frame_params)
        format.html { redirect_to frame_url(@frame), notice: "Frame was successfully updated." }
        format.json { render :show, status: :ok, location: @frame }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frames/1 or /frames/1.json
  def destroy
    @frame.destroy!

    respond_to do |format|
      format.html { redirect_to frames_url, notice: "Frame was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frame
      @frame = Frame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def frame_params
      params.require(:frame).permit(:name, :style, :url, :size, :retail, :paid)
    end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]

  # GET /parts or /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1 or /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts or /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to part_url(@part), notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1 or /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to part_url(@part), notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1 or /parts/1.json
  def destroy
    @part.destroy!

    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:name, :part_type, :url, :retail, :paid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/frames/_form.html.erb
<%= form_with(model: frame) do |form| %>
  <% if frame.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(frame.errors.count, "error") %> prohibited this frame from being saved:</h2>

      <ul>
        <% frame.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :retail, style: "display: block" %>
    <%= form.text_field :retail %>
  </div>

  <div>
    <%= form.label :paid, style: "display: block" %>
    <%= form.text_field :paid %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/frames/_frame.html.erb
<div id="<%= dom_id frame %>">
  <p>
    <strong>Name:</strong>
    <%= frame.name %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= frame.style %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= frame.url %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= frame.size %>
  </p>

  <p>
    <strong>Retail:</strong>
    <%= frame.retail %>
  </p>

  <p>
    <strong>Paid:</strong>
    <%= frame.paid %>
  </p>

</div>

app/views/frames/edit.html.erb
<h1>Editing frame</h1>

<%= render "form", frame: @frame %>

<br>

<div>
  <%= link_to "Show this frame", @frame %> |
  <%= link_to "Back to frames", frames_path %>
</div>

app/views/frames/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Frames</h1>

<div id="frames">
  <% @frames.each do |frame| %>
    <%= render frame %>
    <p>
      <%= link_to "Show this frame", frame %>
    </p>
  <% end %>
</div>

<%= link_to "New frame", new_frame_path %>

app/views/frames/new.html.erb
<h1>New frame</h1>

<%= render "form", frame: @frame %>

<br>

<div>
  <%= link_to "Back to frames", frames_path %>
</div>

app/views/frames/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @frame %>

<div>
  <%= link_to "Edit this frame", edit_frame_path(@frame) %> |
  <%= link_to "Back to frames", frames_path %>

  <%= button_to "Destroy this frame", @frame, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFpvBench</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parts/_form.html.erb
<%= form_with(model: part) do |form| %>
  <% if part.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :part_type, style: "display: block" %>
    <%= form.text_field :part_type %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :retail, style: "display: block" %>
    <%= form.text_field :retail %>
  </div>

  <div>
    <%= form.label :paid, style: "display: block" %>
    <%= form.text_field :paid %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<div id="<%= dom_id part %>">
  <p>
    <strong>Name:</strong>
    <%= part.name %>
  </p>

  <p>
    <strong>Part type:</strong>
    <%= part.part_type %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= part.url %>
  </p>

  <p>
    <strong>Retail:</strong>
    <%= part.retail %>
  </p>

  <p>
    <strong>Paid:</strong>
    <%= part.paid %>
  </p>

</div>

app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to "Show this part", @part %> |
  <%= link_to "Back to parts", parts_path %>
</div>

app/views/parts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Parts</h1>

<div id="parts">
  <% @parts.each do |part| %>
    <%= render part %>
    <p>
      <%= link_to "Show this part", part %>
    </p>
  <% end %>
</div>

<%= link_to "New part", new_part_path %>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to "Back to parts", parts_path %>
</div>

app/views/parts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @part %>

<div>
  <%= link_to "Edit this part", edit_part_path(@part) %> |
  <%= link_to "Back to parts", parts_path %>

  <%= button_to "Destroy this part", @part, method: :delete %>
</div>